### ISSUE TITLE
When do you release codes and paper?

### ISSUE THREAD

**Issue by ByeongHyunPak** [vignywang/SAMFeat#1]
Hi, I'm interested with your work.

When do you release codes and paper?

Thank you :)

**Comment by Wujingqian** [comment]
Hi, thanks for the interest.
The paper can be found here: http://arxiv.org/abs/2309.16992
The code will be released soon. Please follow our github project. Thanks.

**Comment by Wujingqian** [comment]
Hi, thanks for the interest.
The paper can be found here: http://arxiv.org/abs/2309.16992
The code will be released soon. Please follow our github project. Thanks.
